import type { NextPage } from 'next'
import Head from 'next/head'
import AddForm from '../components/AddForm'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex justify-between max-w-[700px]'>
        <div className='text-red-400'>
          <h1>Hello Next.js</h1>
        </div>
        <div className='border ' />
        <div className='text-blue-400'>are</div>
        <div className='border ' />
        <div className='text-green-400'>
          <h1>here</h1>
          <AddForm />
        </div>
        <div className='border ' />
      </div>
    </div>
  )
}

export default Home
